Update test.yml

diff --git a/.github/workflows/test.yml b/.github/workflows/test.yml
--- a/.github/workflows/test.yml
+++ b/.github/workflows/test.yml
@@ -42,6 +42,7 @@ jobs:
           export DISPLAY=:99
           Xvfb :99 -ac -screen 0 1280x1024x24 > /dev/null 2>&1 &
           xvfb_pid=$!
-          npm test || echo "Tests failed, but continue."
-          kill -9 $xvfb_pid
-          ps -ef  # To check if any process is still running
+          npm test
+          echo "Tests completed with status $?"
+          kill $xvfb_pid || echo "Failed to kill Xvfb"
+          ps -ef | grep Xvfb
